# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jakarta REST TCK - 6.2

on:
  push:
    branches:
      - '6.2'
    paths:
      - 'pom.xml'
      - 'providers/**'
      - 'resteasy-bom/**'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-dependencies-bom/**'
      - 'resteasy-security/**'
      - 'server-adapters/resteasy-undertow-cdi/**'
      - 'wildfly/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/resteasy-tck.yml'
      - 'pom.xml'
      - 'providers/**'
      - 'resteasy-bom/**'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-dependencies-bom/**'
      - 'resteasy-security/**'
      - 'server-adapters/resteasy-undertow-cdi/**'
      - 'wildfly/**'

  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  workflow_dispatch:
    inputs:
      os:
        description: "Runner OS"
        required: true
        default: "ubuntu-latest"
        type: string
      javaVersion:
        description: "Java Version"
        required: true
        default: "11"
        type: string

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  resteasy-build:
    uses: /.github/workflows/shared-resteasy-build.yml
    with:
      resteasy-branch: ${{ inputs.resteasy-branch }}
      resteasy-repo: ${{ inputs.resteasy-repo }}

  run-tck:
    runs-on: ubuntu-latest
    needs: resteasy-build
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17', '21']

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: resteasy-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: |
          tar -xzf resteasy-maven-repository.tar.gz -C ~
      - name: Checkout RESTEasy TCK Runner
        uses: actions/checkout@v4
        with:
          repository: resteasy/resteasy-tck-runner
          path: resteasy-tck-runner
          ref: 'jakarta-rest-3.1'
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Run the Jakarta REST TCK - JDK ${{ matrix.java }}
        run:  |
          echo "RESTEASY_VERSION=${{ needs.resteasy-build.outputs.resteasy-version }}"
          cd resteasy-tck-runner
          mvn clean install -U -B -fae -Dtck.debug.log=true -Dversion.org.jboss.resteasy="${{ needs.resteasy-build.outputs.resteasy-version }}"
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports-${{ matrix.os }}-${{ matrix.java }}
          path: |
            '**/surefire-reports/'
            '**/failsafe-reports/'
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'
